-- 코드를 입력하세요



SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT (DISTINCT USER_ID) PUCHASED_USERS, ROUND(COUNT (DISTINCT USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) PUCHASED_RATIO
FROM ONLINE_SALE S JOIN USER_INFO I USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH


                                                                                                                          