-- 코드를 입력하세요


SELECT CONCAT('/home/grep/src/',FILE.BOARD_ID,'/',FILE.FILE_ID,FILE.FILE_NAME,FILE.FILE_EXT) FILE_PATH
FROM 
(SELECT * 
FROM USED_GOODS_BOARD 
ORDER BY VIEWS DESC
LIMIT 1) BOARD JOIN USED_GOODS_FILE FILE ON BOARD.BOARD_ID = FILE.BOARD_ID
ORDER BY FILE.FILE_ID DESC


