-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE TOTAL_SALES
FROM FOOD_PRODUCT LEFT JOIN FOOD_ORDER USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE,"%Y%m") = "202205"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID